version: '3'
services:
  mysql:
    image: ivinco/test_task_mysql_hn:1
    ports:
      - "3307:3306"
    container_name: "ivinco_test_mysql"
  php:
    build:
      context: .
      dockerfile: Dockerfile_php
    container_name: "ivinco_test_php"
    depends_on:
      - "mysql"
    command: [ "/tmp/wait-for", "mysql:3306", "-t", "1000", "--", "php", "/tmp/test.php" ]