version: '3.4'
services:
  mysql:
    image: ivinco/test_task_mysql_hn:1
    ports:
      - "3307:3306"
    container_name: "ivinco_test_mysql"
  php:
    build:
      context: .
      dockerfile: Dockerfile_php
    container_name: "ivinco_test_php"
    depends_on:
      - "mysql"
    command: [ "/tmp/wait-for", "mysql:3306", "-t", "1000", "--", "php", "/tmp/test.php" ]
  nagios:
    ###Add mysql-client to quick check. Probably we could use NRPE too
    build:
      context: .
      dockerfile: Dockerfile_nagios
    container_name: nagios
    volumes:
    ###Make configs persistent and add custom scripts
    - etc:/opt/nagios/etc
    - var:/opt/nagios/var
    - ./plugins:/opt/Custom-Nagios-Plugins
    - ./cfg:/opt/nagios/etc/conf.d/
    ports:
      - 81:80
    links:
      ###Link to mysql to access image directly
      - mysql
volumes:
  etc:
  var:
  plugins:
  cfg:
 


